### ISSUE TITLE
Add dll compile code

### ISSUE THREAD

**Issue by syleishere** [Wanna-Pizza/FletDropZone#1]
Looks interesting, the code to compile the dll is missing however so be useless to anyone.

**Comment by Wanna-Pizza** [comment]
> Looks interesting, the code to compile the dll is missing however so be useless to anyone.

I don't care lmao. I just publish it, you can crack dll if you want.. 

Such repos I doing for myself only. I just drop the link. If anyone wants it - they will use it.
